### ISSUE TITLE
Missing spec files

### ISSUE THREAD

**Issue by lberge17** [learn-co-curriculum/partial-locals-reading#20]
The lab is telling me I need to run local tests, but when I ran learn I got "This directory doesn't appear to have any specs in it." I then looked at the code and couldn't find any spec files. I looked at the GitHub repo and didn't see any there either. I'm not sure if the error is the missing spec files or the "run local tests" part of the lab.

**Comment by Sillhouette** [comment]
This can be fixed by doing the following:

Add `gem 'rspec-rails', ">= 2.0.0.beta"` to the gemfile
Run `bundle install` 
Run `rails generate rspec:install`
Run `learn test`
Run `learn submit`

This adds spec files to the lab so that it can be properly submitted

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm not seeing any instruction to run local tests for this README. It doesn't require tests to pass in order to complete, so I'm going to close it for now. If we've misinterpreted this request or this issue is intended for another lesson, please re-open the issue and we'll take another look. Thanks for contributing!

**Comment by Sillhouette** [comment]
Hey Drake. The Learn.co website is treating this readme as if it is a lab with tests.

**Comment by eclectic-coding** [comment]
It would be helpful if the README.md included directions to add directions to add the tests:
```
Add gem 'rspec-rails', ">= 2.0.0.beta" to the gemfile
Run bundle install
Run rails generate rspec:install
Run learn test
Run learn submit
```
I think this approach would teach students how to add RSPEC to a rails project.

**Comment by Donnadieu** [comment]
@maxwellbenton Would it be possible to re-open this issue? This is still a problem today.

**Comment by ChrstphGrnr** [comment]
@maxwellbenton I second Omar's question, this just came up this morning with a student in AAQ.

**Comment by maxwellbenton** [comment]
Hi @lberge17, @Sillhouette, @eclectic-coding, @Donnadieu, and @ChrstphGrnr,

Thank you for letting us know about this lesson. This issue was due to Learn misinterpreting the lesson type based on the contents of the repository (a `test` folder was present but with no tests). The RSpec solution is good to know, but I've gone ahead and removed the `test` folder which should resolve this issue going forward. Learn is now interpreting this lesson as a code-along requiring work to be submitted only.

I've verified the change in Learn on my end for the online-web-sp-000 batch, so I am going to go ahead and reclose this issue, but please let me know if it is still occurring.

Thank you all!
